### ISSUE TITLE
./jssh: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./jssh)

### ISSUE THREAD

**Issue by undefined-moe** [leizongmin/jssh#19]
建议使用静态链接（？

**Comment by leizongmin** [comment]
请问你这个是在哪个 Linux 发行版上出现的问题？

**Comment by undefined-moe** [comment]
centos 7
（虽然CentOS很蠢但是作为一个shell工具兼容各大系统是必要的

**Comment by leizongmin** [comment]
这种情况建议用 go 自行在目标系统编译 jssh，执行项目代码的 `./build.js` 就可以了

**Comment by undefined-moe** [comment]
ubuntu 1604 (阿里云镜像) 同样复现该问题

**Comment by leizongmin** [comment]
release 的二进制文件是在 ubuntu 20.04 上构建的，可能操作系统版本太高了。可能跟 github.com/lithdew/quickjs 这个依赖有关

**Comment by undefined-moe** [comment]
可以考虑workflow加个ubuntu version matrix？

**Comment by leizongmin** [comment]
改成 ubuntu 16.04 构建了，你试试还有没有问题 https://github.com/leizongmin/jssh/releases/tag/current

**Comment by undefined-moe** [comment]
1604测试通过。

~~顺便获得了更小的文件体积 这不香吗~~
